# Generated by Django 5.0.6 on 2024-05-26 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='signs_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='signs_videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='signs_audios/')),
                ('dock', models.FileField(blank=True, null=True, upload_to='signs_dock/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertisements.category')),
            ],
            options={
                'db_table': 'roadsigns',
            },
        ),
    ]
